
*** Variables ***
#TEST TAGS REQUIRING EXCLUSIONS FROM THE PAGE
@{excludetaglist}     ARTICLE

# AREAS FROM THE PICTURE TO BE EXCLUDED FROM COMPARISON (SO THAT TESTS WONT FAIL IN CASE OF CHANGING PARTS OF THE PICTURE)
# VALUES TO DETERMINE AREA ARE (MINX , MINY , MAXX , MAXY). MULTIPLE AREAS SEPARATED BY | CHARACTER
# VARIABLE NAME MATCHES THE TAG EXPLICITELY
@{ARTICLE}			332,44,364,47|0,10,10,20