version: '3.7'

services:
  robo:
    container_name: "python-automation"
    image: "${TEST_AUTOMATION_REPOSITORY}"
    networks:
      - internal
      - stonehenge-network
networks:
  internal:
    external: false
  stonehenge-network:
    external: true

volumes:
  db_data:
